const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_SUCESS = 'LOGIN_SUCESS';
const ERROR_MSG = 'ERROR_MSG';
const LOAD_List_DATA = 'LOAD_List_DATA';
const LOG_OUT = 'LOG_OUT';
const RESET_PASS = 'RESET_PASS';
const LET_REDIRECT = 'LET_REDIRECT';

export { REGISTER_SUCCESS, LOGIN_SUCESS, ERROR_MSG, LOAD_List_DATA, LOG_OUT, RESET_PASS, LET_REDIRECT };