const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_SUCESS = 'LOGIN_SUCESS';
const ERROR_MSG = 'ERROR_MSG';
const LOAD_List_DATA = 'LOAD_List_DATA';

export { REGISTER_SUCCESS, LOGIN_SUCESS, ERROR_MSG, LOAD_List_DATA };